### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by pmaingi** [serpel/Opengradebook#40]
Hi serpel,

When i try to input username/password here http://inedhn.com/ it never works.What are the correct credentials.I would love to use the system to learn ruby

**Comment by serpel** [comment]
Sorry to answer until today, http://inedhn.com/ this app is a production version of this app, i recommend to install the project on your local environment, following the instructions on readme text from this repo.

**Comment by pmaingi** [comment]
Ok. Thank you.
