### ISSUE TITLE
modules supported

### ISSUE THREAD

**Issue by kirantpatil** [serpel/Opengradebook#45]
Hi,

May I know what modules does it support ?

Why it is not updated to Rails 4 or 5 ?

Thanks.

**Comment by serpel** [comment]
Sorry for the delay, my Gmail hide this messages, because just required a lot time and effort migrate it, in the actuality I'm doing little fix but I'm focusing on other projects, related to mobile development. Sorry.

**Comment by kirantpatil** [comment]
Thanks for your response.
